/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saa;

/**
 *
 * @author fnyakoe
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
      
     private Connection con;
    private Statement st;
    private ResultSet rs;
    private PreparedStatement pst;
    public Manager() {
        initComponents();
        connection();
        show_user();
        show_stock();
    }
      public void connection(){
       try{
          
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant","root","");
          String sql = "SELECT * FROM torders";
          String sql2 = "SELECT*FROM stock_details";
          st=con.createStatement();
          rs=st.executeQuery(sql);
       } 
       catch (SQLException er){
           JOptionPane.showMessageDialog(this, er.getMessage());
       }
       
       
    }
       public ArrayList<User> userlist(){
    ArrayList<User> userslist = new ArrayList<>();
    try{
   String query1="SELECT*FROM torders" ;
   Statement st = con.createStatement();
   ResultSet rs = st.executeQuery(query1);
   User user;
   while (rs.next()){
       user=new User(rs.getInt("torderID"),rs.getInt("tableID"),rs.getString("orderDets"),rs.getString("Paymethod"),rs.getDouble("Total"),rs.getString("Review"));
       userslist.add(user);
       
   }
           }
    catch (SQLException er){
           JOptionPane.showMessageDialog(this, er.getMessage());
       }
       
       return userslist;
}
public void show_user(){
    ArrayList<User> list = userlist();
    DefaultTableModel model = (DefaultTableModel)Ordertable.getModel();
    Object[] row = new Object[6];
    for (int i =0;i<list.size();i++){
        row[0]=list.get(i).gettorderID();
        row[1]= list.get(i).gettableID();
        row[2]= list.get(i).getorderDets();
        row[3]= list.get(i).getPaymethod();
        row[4]= list.get(i).getTotal();
        row[5]= list.get(i).getReview();
        model.addRow(row);
    }
    
}
  public ArrayList<Stock> stocklist(){
    ArrayList<Stock> stocklist = new ArrayList<>();
    try{
   String query2="SELECT*FROM stock_details" ;
   Statement st = con.createStatement();
   ResultSet rs = st.executeQuery(query2);
   Stock stock;
   while (rs.next()){
       stock=new Stock(rs.getInt("ID"),rs.getString("Itemname"),rs.getInt("Quantity"));
       stocklist.add(stock);
       
   }
           }
    catch (SQLException er){
           JOptionPane.showMessageDialog(this, er.getMessage());
       }
       
       return stocklist;
}
  public void show_stock(){
    ArrayList<Stock> list = stocklist();
    DefaultTableModel model = (DefaultTableModel)Stocktable.getModel();
    Object[] row = new Object[3];
    for (int i =0;i<list.size();i++){
        row[0]=list.get(i).getID();
        row[1]= list.get(i).getItemname();
        row[2]= list.get(i).getQuantity();
       
        model.addRow(row);
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Stocktable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ordertable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taOrder = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        Stocktable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Stocktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Itemname", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Stocktable.setRowHeight(20);
        jScrollPane2.setViewportView(Stocktable);

        jTabbedPane1.addTab("STOCK", jScrollPane2);

        Ordertable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderId", "TableId", "OrderDets", "PaymentMethod", "Total", "Review"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ordertable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        Ordertable.setRowHeight(24);
        jScrollPane1.setViewportView(Ordertable);
        if (Ordertable.getColumnModel().getColumnCount() > 0) {
            Ordertable.getColumnModel().getColumn(2).setPreferredWidth(6);
        }

        jTabbedPane1.addTab("ORDERS", jScrollPane1);

        jLabel1.setText("MANAGER");

        jLabel2.setText("SEARCH FOR AN ORDER:");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        taOrder.setColumns(20);
        taOrder.setRows(5);
        jScrollPane3.setViewportView(taOrder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1176, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
           new LOG_IN().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try{
          
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant","root","");
          String sql = "SELECT * FROM torders WHERE torderID='"+txtID.getText()+"'";
          st=con.createStatement();
          rs=st.executeQuery(sql);
          rs.next();
         
          String tableID = rs.getString("tableID");
          String orderDets=rs.getString("orderDets");
          String Paymethod=rs.getString("Paymethod");
          String Total=rs.getString("Total");
          String Review = rs.getString("Review");
         
          
        taOrder.setText("Table "+tableID+'\n'+ orderDets+'\n'+Paymethod+'\n'+"Ksh"+Total+'\n'+Review);
          
                  
          
       } 
       catch (SQLException er){
           JOptionPane.showMessageDialog(this, er.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ordertable;
    private javax.swing.JTable Stocktable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea taOrder;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
